name: Cleanup Old Workflows

on:
    schedule:
        -   cron: '0 0 * * *' # Run daily at 00:00
    workflow_dispatch:

jobs:
    cleanup:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.x'

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install requests

            -   name: Cleanup old workflow runs
                env:
                    TOKEN: ${{ secrets.PAT }}
                run: |
                    python - <<EOF
                    import json
                    import re
                    from datetime import datetime, timedelta
                    import requests
                    
                    def get_workflow_runs(url):
                        headers = {'Authorization': f"token {TOKEN}"}
                        response = requests.get(url, headers=headers)
                        if response.status_code != 200:
                            print(f"Error: {response.text}")
                            return [], None
                        link_header = response.headers.get('Link')
                        next_url_ = None
                        if link_header:
                            match = re.search(r'<(https://api.github.com/[^>]+)>;\s*rel="next"', link_header)
                            if match:
                                next_url_ = match.group(1)
                        return json.loads(response.text)['workflow_runs'], next_url_
                    
                    def delete_workflow_run(run_id):
                        url = f"https://api.github.com/repos/Hamza417/Inure/actions/runs/{run_id}"
                        headers = {'Authorization': f"token {TOKEN}"}
                        response = requests.delete(url, headers=headers)
                        if response.status_code != 204:
                            print(f"Error: {response.text}")
                        else:
                            print(f"Deleted workflow run {run_id}")
                    
                    old_date = datetime.now() - timedelta(days=14)
                    next_url = f"https://api.github.com/repos/Hamza417/Inure/actions/runs"
                    
                    while next_url:
                        workflow_runs, next_url = get_workflow_runs(next_url)
                        for run in workflow_runs:
                            created_at = datetime.strptime(run['created_at'], '%Y-%m-%dT%H:%M:%SZ')
                            if created_at < old_date:
                                delete_workflow_run(run['id'])
                    
                    
                    print("Done")
                    EOF
