name: Auto Merge Crowdin Pull Requests
on:
  pull_request:
    types:
      - opened

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from Crowdin
        id: check-crowdin-pr
        run: echo "::set-output name=is_crowdin_pr::$(echo "${{ github.event.pull_request.title }}" | grep -q 'New Crowdin updates' && echo true || echo false)"

      - name: Merge Crowdin PR
        if: steps.check-crowdin-pr.outputs.is_crowdin_pr == "true"
        run: |
          # Replace with your GitHub token and repository information
          GITHUB_TOKEN=${{ secrets.TOKEN }}

          # Merge the pull request
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -d '{
              "merge_method": "merge"
            }' "$GITHUB_API_URL/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
